site_name: Pinferencia
repo_url: https://github.com/underneathall/pinferencia
repo_name: Pinferencia
edit_uri: blob/main/docs/
copyright: Copyright © 2020-2022 Jiuhe WANG underneathall.com, underneathall.app All Rights Reserved.
theme:
  name: material
  language: en
  custom_dir: docs/overrides
  features:
    - search.suggest
    - navigation.expand
    # - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - navigation.tabs
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png
  icon:
    # logo: material/horse
    repo: fontawesome/brands/github

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wjiuhe

extra_css:
    - 'underneathall/css/termynal.css'
    - 'underneathall/css/custom.css'
extra_javascript:
    - 'underneathall/js/termynal.js'
    - 'underneathall/js/custom.js'

plugins:
  - search
  - minify:
      minify_html: true
  - i18n:
      material_alternate: true
      default_language: en
      languages:
        en:
          name: English
          build: true
        re:
          name: Seriouly, Doc
          build: true
        zh:
          name: 中文
          build: true
        rc:
          name: 有点不一样文档
          build: true
      nav_translations:
        zh:
          Home: 首页

          # introduction
          Introduction: 介绍
          Overview: 概述
          Pinferencia is different?: Pinferencia 有何不同?

          # get started
          Get Started: 快速上手
          Install: 安装
          Tutorial: 使用教程
          Serve a Simple JSON Model: 启动一个简单的 JSON 模型
          Serve a Function: 启动一个函数
          Serve PyTorch MNIST Model: 启动 PyTorch MNIST 模型
          MNIST Bonus: MNIST 特别任务
          What's Next: 下一步

          # how-to guides
          How-to Guides: 实战指南
          Use Pinferencia with HuggingFace: 上线 HuggingFace 模型
          HuggingFace: HuggingFace

          NLP Tasks: 自然语言处理
          Install Dependencies: 安装依赖
          Bert: Bert
          Text Generation - GPT2: 文本生成 - GPT2
          Translation - Google T5: 翻译 - Google T5

          Vision Tasks: 计算机视觉任务
          Image Classification: 图像识别

          Define Request and Response Schema: 定义请求和响应 Schema
          Custom Templates: 自定义模版

          # reference
          Reference: 参考文档
          Other Machine Learning Frameworks: 其它机器学习框架
          Register Models: 注册模型
          Handlers: Handlers
          REST API: REST API
          Frontend Requirements: 前端使用条件
          CLI: 命令行界面

          # background
          Background: 背景
          About Models: 关于模型

        rc:
          Home: 首页

          # introduction
          Introduction: 介绍
          Overview: 概述
          Pinferencia is different?: Pinferencia 有何不同?

          # get started
          Get Started: 快速上手
          Install: 安装
          Tutorial: 使用教程
          Serve a Simple JSON Model: 启动一个简单的 JSON 模型
          Serve a Function: 启动一个函数
          Serve PyTorch MNIST Model: 启动 PyTorch MNIST 模型
          MNIST Bonus: MNIST 特别任务
          What's Next: 下一步

          # how-to guides
          How-to Guides: 实战指南
          Use Pinferencia with HuggingFace: 上线 HuggingFace 模型
          HuggingFace: HuggingFace

          NLP Tasks: 自然语言处理
          Install Dependencies: 安装依赖
          Bert: Bert
          Text Generation - GPT2: 文本生成 - GPT2
          Translation - Google T5: 翻译 - Google T5

          Vision Tasks: 计算机视觉任务
          Image Classification: 图像识别

          Define Request and Response Schema: 定义请求和响应 Schema
          Custom Templates: 自定义模版

          # reference
          Reference: 参考文档
          Other Machine Learning Frameworks: 其它机器学习框架
          Register Models: 注册模型
          Handlers: Handlers
          REST API: REST API
          Frontend Requirements: 前端使用条件
          CLI: 命令行界面

          # background
          Background: 背景
          About Models: 关于模型

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Introduction:
    - Overview: introduction/overview/index.md
    - Pinferencia is different?: introduction/pinferencia-is-different/index.md
  - Get Started:
    - Install: get-started/install/index.md
    - Tutorial:
      - Introduction: get-started/introduction/index.md
      - Serve a Simple JSON Model: get-started/serve-a-json-model/index.md
      - Serve a Function: get-started/serve-a-function/index.md
      - Serve PyTorch MNIST Model: get-started/pytorch-mnist/index.md
      - MNIST Bonus: get-started/pytorch-mnist/bonus.md
    - What's Next: get-started/other-models/index.md
  - How-to Guides:
    - Use Pinferencia with HuggingFace:
      - Install Dependencies: how-to-guides/huggingface/dependencies/index.md
      - NLP Tasks:
        - Bert: how-to-guides/huggingface/pipeline/nlp/bert/index.md
        - Text Generation - GPT2: how-to-guides/huggingface/pipeline/nlp/text-generation/index.md
        - Translation - Google T5: how-to-guides/huggingface/pipeline/nlp/translation/index.md
      - Vision Tasks:
        - Image Classification: how-to-guides/huggingface/pipeline/vision/index.md
    - Define Request and Response Schema: how-to-guides/schema/index.md
    - Custom Templates: how-to-guides/custom-templates/index.md
  - Reference:
    - Other Machine Learning Frameworks: reference/models/machine-learning/index.md
    - Register Models: reference/models/register/index.md
    - Handlers: reference/handlers/index.md
    - Frontend Requirements: reference/frontend/requirements/index.md
    - REST API: reference/restapi/index.md
    - CLI: reference/cli/index.md
    #   - Customize: frontend/custom/index.md
    #   - Default Task Type: frontend/task/index.md
    #   - Connect to Other Backends: frontend/other-backends/index.md
    # - Backend:
    #   - Customize: backend/custom/index.md
    #   - Generate Client: create-client/index.md
  - Background:
    - About Models: background/models/home/index.md
    # - CLI Flags: cli/index.md
